package pl.rea.client.webmethods.dictionaries;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "dicsService", targetNamespace = "dictionaries", wsdlLocation = "http://localhost:6666/dictionaries?wsdl")
public class DicsService_Service
    extends Service
{

    private final static URL DICSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DICSSERVICE_EXCEPTION;
    private final static QName DICSSERVICE_QNAME = new QName("dictionaries", "dicsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6666/dictionaries?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DICSSERVICE_WSDL_LOCATION = url;
        DICSSERVICE_EXCEPTION = e;
    }

    public DicsService_Service() {
        super(__getWsdlLocation(), DICSSERVICE_QNAME);
    }

    public DicsService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DICSSERVICE_QNAME, features);
    }

    public DicsService_Service(URL wsdlLocation) {
        super(wsdlLocation, DICSSERVICE_QNAME);
    }

    public DicsService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DICSSERVICE_QNAME, features);
    }

    public DicsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DicsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DicsService
     */
    @WebEndpoint(name = "DicsServicePort")
    public DicsService getDicsServicePort() {
        return super.getPort(new QName("dictionaries", "DicsServicePort"), DicsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DicsService
     */
    @WebEndpoint(name = "DicsServicePort")
    public DicsService getDicsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("dictionaries", "DicsServicePort"), DicsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DICSSERVICE_EXCEPTION!= null) {
            throw DICSSERVICE_EXCEPTION;
        }
        return DICSSERVICE_WSDL_LOCATION;
    }

}
